//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace YueQianQian.Model
{

    [JsonObject(MemberSerialization.OptIn), Table(Name = "bookmark")]
    public partial class BookmarkEntity
    {

        [JsonProperty, Column(Name = "id", IsPrimary = true, IsIdentity = true)]
        public int Id { get; set; }

        [JsonProperty, Column(Name = "click_count")]
        public short? ClickCount { get; set; }

        [JsonProperty, Column(Name = "created_at", DbType = "datetime")]
        public DateTime? CreatedAt { get; set; }

        [JsonProperty, Column(Name = "description", DbType = "varchar(4096)")]
        public string Description { get; set; } = string.Empty;

        [JsonProperty, Column(Name = "last_click", DbType = "datetime")]
        public DateTime? LastClick { get; set; }

        [JsonProperty, Column(Name = "title")]
        public string Title { get; set; } = string.Empty;

        [JsonProperty, Column(Name = "url", DbType = "varchar(1024)")]
        public string Url { get; set; } = string.Empty;

        [JsonProperty, Column(Name = "user_id")]
        public int? UserId { get; set; }
        [JsonProperty, Column(Name = "favicon", DbType = "varchar(1024)")]
        public string Favicon { get; set; } = string.Empty;


    }

}
