//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace YueQianQian.Model
{

    [JsonObject(MemberSerialization.OptIn), Table(Name = "note")]
    public partial class NoteEntity
    {

        [JsonProperty, Column(Name = "id", IsPrimary = true, IsIdentity = true)]
        public int Id { get; set; }

        [JsonProperty, Column(Name = "content", DbType = "text")]
        public string Content { get; set; } = string.Empty;

        [JsonProperty, Column(Name = "created_at", DbType = "datetime")]
        public DateTime? CreatedAt { get; set; }

        [JsonProperty, Column(Name = "tag_id")]
        public int? TagId { get; set; }

        [JsonProperty, Column(Name = "user_id")]
        public int UserId { get; set; }

    }

}
