//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace YueQianQian.Model
{

    [JsonObject(MemberSerialization.OptIn), Table(Name = "tag_bookmark")]
    public partial class TagBookmarkEntity
    {

        [JsonProperty, Column(Name = "bookmark_id", IsPrimary = true)]
        public int BookmarkId { get; set; }

        [JsonProperty, Column(Name = "tag_id", IsPrimary = true)]
        public int TagId { get; set; }

        /// <summary>
        /// 导航属性  书签
        /// </summary>
        [Navigate(nameof(BookmarkId))]
        public BookmarkEntity Bookmark { get; set; }
        /// <summary>
        /// 导航属性  目录
        /// </summary>
        [Navigate(nameof(TagId))]
        public TagEntity TagEntity { get; set; }

    }

}
